language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  matrix:
    - DJANGO=2.2
    - DJANGO=3.0

install:
  - pip install -r requires.txt
  - pip install Django~=$DJANGO
  - pip install codecov mypy django-stubs

script:
  - cd src
  - python ./manage.py makemigrations --check --dry-run
  - python -m coverage run ./manage.py test -v3
  - mypy --config-file=../mypy.ini video_transcoding

after_success: codecov
